version: 0.0
os: linux
files:
  - source: workshop-1.0.jar
    destination: /opt/application
hooks:
  ApplicationStop:
    - location: shutdown_server.sh
      timeout: 180
  ApplicationStart:
    - location: startup_server.sh
      timeout: 180