version: 0.2

phases:
  build:
    commands:
      - mvn clean install

artifacts:
  files:
    - target/workshop-test-1.0-SNAPSHOT.jar
    - appspec.yml
    - pipeline_scripts/startup_server.sh
  discard-paths: yes