version: 0.2

phases:
  build:
    commands:
      - mvn clean package

artifacts:
  files:
    - target/workshop-1.0.jar
    - appspec.yml
    - pipeline_scripts/startup_server.sh
    - pipeline_scripts/shutdown_server.sh
  discard-paths: yes